/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'bookingId' : IDL.Text,
  'gamePackage' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'groupSize' : IDL.Nat,
});
export const Time = IDL.Int;
export const Score = IDL.Record({
  'date' : Time,
  'game' : IDL.Text,
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deleteBooking' : IDL.Func([IDL.Text], [], []),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'bookingId' : IDL.Text,
    'gamePackage' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'groupSize' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Score = IDL.Record({
    'date' : Time,
    'game' : IDL.Text,
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    'addBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteBooking' : IDL.Func([IDL.Text], [], []),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };